dynamic_data_file:
  - C:/Users/nguyenta/Documents/GitHub/hydroecolstm/examples/2_streamflow_isotope_simulation/data/timeseries_data.csv

static_data_file:
  - C:/Users/nguyenta/Documents/GitHub/hydroecolstm/examples/2_streamflow_isotope_simulation/data/static_data.csv

output_directory:
  - C:/Users/nguyenta/Documents/GitHub/hydroecolstm/examples/2_streamflow_isotope_simulation/results

input_static_features:
  - area

input_dynamic_features:
  - precipitation
  - oxygen_isotope_precipitation
  - temperature
#  - relative_humidity

target_features:
  - streamflow
  - oxygen_isotope_streamflow

object_id:
  - Erlenbach
  - Alp

train_period: 
  - 2016-06-01 00:00
  - 2018-05-31 00:00

valid_period: 
  - 2018-06-10 00:00
  - 2019-05-31 00:00

test_period: 
  - 2015-06-19 00:00
  - 2016-05-31 00:00

model_class: LSTM

Regression:
  activation_function:
    - Identity
  num_neurons:
    - None
  num_layers: 1

scaler_input_dynamic_features:
  - Z-score
scaler_input_static_features:
  - None
scaler_target_features:
  - Z-score

hidden_size: 20

num_layers: 2

n_epochs: 300

learning_rate: 0.005

dropout: 0.3

warmup_length: 15

loss_function: RMSE

sequence_length: 120

batch_size: 2

patience: 10

eval_function: NSE


#print(objective(data['y_train'], data['y_train_simulated']))
#({'Erlenbach': tensor([0.4540, 0.6942]), 'Alp': tensor([0.6693, 0.6110])}, tensor(0.6071))

#print(objective(data['y_valid'], data['y_valid_simulated']))
#({'Erlenbach': tensor([0.5142, 0.2563]), 'Alp': tensor([0.6173, 0.2676])}, tensor(0.4139))

#print(objective(data['y_test'], data['y_test_simulated']))
#({'Erlenbach': tensor([0.6598, 0.8134]), 'Alp': tensor([0.6900, 0.5840])}, tensor(0.6868))