dynamic_data_file:
  - C:/hydroecolstm/examples/2_streamflow_isotope_simulation/data/timeseries_data.csv

static_data_file:
  - C:/hydroecolstm/examples/2_streamflow_isotope_simulation/data/static_data.csv

output_directory:
  - C:/hydroecolstm/examples/2_streamflow_isotope_simulation/results

input_static_features:
  - area

input_dynamic_features:
  - precipitation
  - oxygen_isotope_precipitation
  - temperature

target_features:
  - streamflow
  - oxygen_isotope_streamflow

object_id:
  - Erlenbach
  - Alp

train_period: 
  - 2016-06-01 00:00
  - 2018-05-31 00:00

valid_period: 
  - 2018-06-01 00:00
  - 2019-05-31 00:00

test_period: 
  - 2015-06-01 00:00
  - 2016-05-31 00:00

model_class: LSTM

Regression:
  activation_function:
    - Identity
  num_neurons:
    - None
  num_layers: 1

scaler_input_dynamic_features:
  - Z-score
scaler_input_static_features:
  - None
scaler_target_features:
  - Z-score

# hidden_size: tune.grid_search([5, 10, 15, 20, 25])
hidden_size: tune.randint(5, 30)

# num_layers: tune.grid_search([1, 2])
num_layers: tune.grid_search([1, 2])

# n_epochs: 300
n_epochs: tune.randint(150, 300)

# learning_rate: tune.grid_search([0.001, 0.005, 0.01]) 
learning_rate: tune.choice([0.001, 0.002, 0.005, 0.01])

# dropout: 0.2
dropout: 0.3

# warmup_length: 30
warmup_length: 30

loss_function: RMSE

# tune.grid_search([50, 100, 150, 200])
sequence_length: 100

#tune.grid_search([2, 4, 6, 8])
batch_size: tune.grid_search([4, 6, 8])

patience: 20

eval_function: NSE