dynamic_data_file:
  - C:/Users/nguyenta/Documents/GitHub/hydroecolstm/examples/2_streamflow_isotope_simulation/data/timeseries_data.csv

static_data_file:
  - C:/Users/nguyenta/Documents/GitHub/hydroecolstm/examples/2_streamflow_isotope_simulation/data/static_data.csv

output_directory:
  - C:/Users/nguyenta/Documents/GitHub/hydroecolstm/examples/2_streamflow_isotope_simulation/results

input_static_features:
  - area

input_dynamic_features:
  - precipitation
  - oxygen_isotope_precipitation
  - temperature
#  - relative_humidity

target_features:
  - streamflow
  - oxygen_isotope_streamflow

object_id:
  - Erlenbach
  - Alp

train_period: 
  - 2016-06-01 00:00
  - 2018-05-31 00:00

valid_period: 
  - 2018-06-10 00:00
  - 2019-05-31 00:00

test_period: 
  - 2015-06-19 00:00
  - 2016-05-31 00:00

model_class: LSTM

Regression:
  activation_function:
    - Identity
  num_neurons:
    - None
  num_layers: 1

scaler_input_dynamic_features:
  - Z-score
scaler_input_static_features:
  - None
scaler_target_features:
  - Z-score

hidden_size: 20

num_layers: 2

n_epochs: 300

learning_rate: 0.005

dropout: 0.3

warmup_length: 15

loss_function: RMSE

sequence_length: 120

batch_size: 2

patience: 10

eval_function: NSE

#({'Erlenbach': tensor([0.3989, 0.6345]), 'Alp': tensor([0.6127, 0.4879])}, tensor(0.5335))
#({'Erlenbach': tensor([0.5654, 0.2006]), 'Alp': tensor([0.6515, 0.1729])}, tensor(0.3976))
#({'Erlenbach': tensor([0.5852, 0.7183]), 'Alp': tensor([0.6745, 0.4936])}, tensor(0.6179))