dynamic_data_file:
  - C:/Users/nguyenta/Documents/GitHub/hydroecolstm/examples/2_streamflow_isotope_simulation/data/timeseries_data.csv

static_data_file:
  - C:/Users/nguyenta/Documents/GitHub/hydroecolstm/examples/2_streamflow_isotope_simulation/data/static_data.csv

output_directory:
  - C:/Users/nguyenta/Documents/GitHub/hydroecolstm/examples/2_streamflow_isotope_simulation/results

input_static_features:
  - area

input_dynamic_features:
  - precipitation
  - oxygen_isotope_precipitation
  - temperature
#  - relative_humidity

target_features:
  - streamflow
  - oxygen_isotope_streamflow

object_id:
  - Erlenbach
  - Alp

train_period: 
  - 2016-05-01 00:00
  - 2018-05-31 00:00

test_period: 
  - 2015-05-01 00:00
  - 2016-05-31 00:00

valid_period: 
  - 2018-05-01 00:00
  - 2019-05-31 00:00

model_class: LSTM

Regression:
  activation_function:
    - Identity
  num_neurons:
    - None
  num_layers: 1

scaler_input_dynamic_features:
  - Z-score
scaler_input_static_features:
  - None
scaler_target_features:
  - Z-score

hidden_size: 20

num_layers: 2

n_epochs: 300

learning_rate: 0.005

dropout: 0.2

warmup_length: 30

loss_function: RMSE

sequence_length: 150

batch_size: 3

patience: 20

eval_function: NSE

#({'Erlenbach': tensor([0.4902, 0.7114]), 'Alp': tensor([0.7224, 0.7151])}, tensor(0.6598))
#({'Erlenbach': tensor([0.6450, 0.6785]), 'Alp': tensor([0.7640, 0.4193])}, tensor(0.6267))
#({'Erlenbach': tensor([0.7067, 0.8795]), 'Alp': tensor([0.7876, 0.5433])}, tensor(0.7293))