dynamic_data_file:
  - C:/Users/nguyenta/Documents/GitHub/time_series.csv
static_data_file:
  - C:/Users/nguyenta/Documents/GitHub/static_attributes.csv
input_static_features:
  - elev_mean
  - slope_mean
  - p_seasonality
  - aridity
  - pet_mean
input_dynamic_features:
  - precipitation_mm_d
  - temperature_mean_degC
target_features:
  - discharge_vol_m3_s
object_id:
  - 2009
  - 2016
  - 2018
  - 2019
  - 2020
  - 2024
  - 2030
  - 2033
train_period: 
  - 2000-01-01 00:00
  - 2010-12-31 00:00
test_period: 
  - 2000-01-01 00:00
  - 2010-12-31 00:00
model_class: LSTM
REG:
  activation_function:
    - Identity
  num_neurons:
    - None
  num_layers: 1
scaler_input_dynamic_features:
  - Z-score
scaler_input_static_features:
  - Z-score
scaler_target_features:
  - MinMaxScaler
hidden_size: 30
num_layers: 1
n_epochs: 150
learning_rate: 0.005
dropout: 0.3
warmup_length: 365
objective_function_name: 1-NSE
static_data_file_forecast:
  - static_data_file
dynamic_data_file_forecast:
  - dynamic_data_file
forecast_period: 
  - 2000-01-01 00:00
  - 2010-12-31 00:00
object_id_forecast:
  - 2011
  - 2029

