scaler_input_dynamic_features:
  - MinMaxScaler
scaler_input_static_features:
  - MinMaxScaler
scaler_target_features:
  - MinMaxScaler
hidden_size: 30
num_layers: 1
activation_function_name: Identity
n_epochs: 50
learning_rate: 0.01
dropout: 0.3
warmup_length: 20
objective_function_name: RMSE
output_dir:
  - C:/Users/nguyenta/Documents/GitHub/hydroecolstm/examples
