dynamic_data_file:
  - C:/Users/nguyenta/Documents/GitHub/hydroecolstm/examples/time_series.csv
input_dynamic_features:
  - precipitation_mm_d
  - temperature_min_degC
  - temperature_mean_degC
  - temperature_max_degC
  - rel_sun_dur
target_features:
  - discharge_vol_m3_s
object_id:
  - 2009
  - 2011
train_period: 
  - 2000-01-01 00:00
  - 2010-01-01 00:00
test_period: 
  - 2000-01-01 00:00
  - 2010-01-01 00:00
REG:
  activation_function:
    - Identity
    - Identity
    - Identity
  num_neurons:
    - 10
    - 20
    - None
  num_layers: 3
scaler_input_dynamic_features:
  - MinMaxScaler
scaler_input_static_features:
  - MinMaxScaler
scaler_target_features:
  - MinMaxScaler
hidden_size: 30
num_layers: 1
n_epochs: 50
learning_rate: 0.02
dropout: 0.3
warmup_length: 20
objective_function_name: RMSE
output_dir:
  - C:/Users/nguyenta/Documents/GitHub/hydroecolstm/examples
