#----------------------------------------------------------------------------#
#           Configuration for training and testing the LSTM network          #
#----------------------------------------------------------------------------#
# Link to the data file (contains input features and targeted data for training)
dynamic_data_file: 
  - C:/Users/nguyenta/Documents/GitHub/HydroEcoLSTM/examples/time_series.csv

static_data_file: 
  - C:/Users/nguyenta/Documents/GitHub/HydroEcoLSTM/examples/static_attributes.csv

# Object ID/Basins for training
object_id:
  - 2009
  - 2011

# Input dynamic features
input_dynamic_features:
  - precipitation_mm_d
  - temperature_mean_degC
  - rel_sun_dur

# Input static features => full list of features at the end of this documentation
input_static_features:
  - p_mean
  - aridity
  - pet_mean
  - p_seasonality

# Target/output features
target_features:
  - discharge_vol_m3_s

# Scaler for target features
scaler_target_features:
  - MinMaxScaler

# Scaler for static features
scaler_input_dynamic_features:
  - MinMaxScaler

# If you did not have input static_features, please leave this empyt
scaler_input_static_features:
  - MinMaxScaler

# Training period with format YYYY-MM-DD
train_period:
  - 2010-01-01
  - 2020-12-31

# Hidden size of the LSTM
hidden_size: 30

# Number of layers
num_layers: 1

# Activation function: "ReLu", "Sigmoid", "Tanh", "Softplus", "Identity"
activation_function_name: Identity

# Dropout layer on the outputs of each LSTM layer except the last layer
# Therefore, this parameter is only used if  num_layers > 1
dropout: 0.4

# Validation period with format YYYY-MM-DD
test_period:
  - 1982-01-01
  - 2009-12-31

# Number of epochs
n_epochs: 150

# Learning rate
learning_rate: 0.005

# warmup_length must be < batch_size
# when calculating the loss, the first warmup_length timesteps will be omitted
warmup_length: 12

# objective function 1-NSE, MSE, RMSE, MAE
objective_function_name: MAE

# optimization method
optim_method: Adam

#----------------------------------------------------------------------------#
# Configuration for forward run (optional input - delete if no required)     #
#    e.g., ungauged basins or prediction with the trained model              #
#----------------------------------------------------------------------------#
dynamic_data_file_test: 
  - dynamic_data_file
static_data_file_test: 
  - static_data_file
object_id_test:
  - 2009
  - 2011
test_period_test:
  - 1982-01-01
  - 2009-12-31